# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "basic-resume-bee1850"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Berkan E.", "Stephen Xu <https://stuxf.dev>"]
license = "Unlicense"
description = "A simple, standard resume, designed to work well with ATS."
repository = "https://github.com/bee1850/basic-typst-resume-template"
keywords = ["cv", "resume", "ATS"]
categories = ["cv"]
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
